# Generated by Django 3.1.5 on 2021-01-27 18:23

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "due",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2021, 1, 28, 18, 23, 38, 553269, tzinfo=utc
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hint",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.AddField(
            model_name="hint",
            name="task",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
            preserve_default=False,
        ),
    ]
