# Generated by Django 3.1.5 on 2021-01-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210127_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='hint',
            field=models.TextField(verbose_name='Hint'),
        ),
    ]
